/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrbitRouteImport } from './routes/orbit'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrbitIndexRouteImport } from './routes/orbit.index'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as OrbitPrivacyRouteImport } from './routes/orbit.privacy'
import { Route as OrbitCreateRouteImport } from './routes/orbit.create'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrbitRoute = OrbitRouteImport.update({
  id: '/orbit',
  path: '/orbit',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrbitIndexRoute = OrbitIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrbitRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrbitPrivacyRoute = OrbitPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => OrbitRoute,
} as any)
const OrbitCreateRoute = OrbitCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => OrbitRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/orbit': typeof OrbitRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reels': typeof ReelsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/orbit/create': typeof OrbitCreateRoute
  '/orbit/privacy': typeof OrbitPrivacyRoute
  '/chat/': typeof ChatIndexRoute
  '/orbit/': typeof OrbitIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/profile': typeof ProfileRoute
  '/reels': typeof ReelsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/orbit/create': typeof OrbitCreateRoute
  '/orbit/privacy': typeof OrbitPrivacyRoute
  '/chat': typeof ChatIndexRoute
  '/orbit': typeof OrbitIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/orbit': typeof OrbitRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reels': typeof ReelsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/orbit/create': typeof OrbitCreateRoute
  '/orbit/privacy': typeof OrbitPrivacyRoute
  '/chat/': typeof ChatIndexRoute
  '/orbit/': typeof OrbitIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/orbit'
    | '/profile'
    | '/reels'
    | '/settings'
    | '/sitemap.xml'
    | '/chat/$threadId'
    | '/orbit/create'
    | '/orbit/privacy'
    | '/chat/'
    | '/orbit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/profile'
    | '/reels'
    | '/settings'
    | '/sitemap.xml'
    | '/chat/$threadId'
    | '/orbit/create'
    | '/orbit/privacy'
    | '/chat'
    | '/orbit'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/orbit'
    | '/profile'
    | '/reels'
    | '/settings'
    | '/sitemap.xml'
    | '/chat/$threadId'
    | '/orbit/create'
    | '/orbit/privacy'
    | '/chat/'
    | '/orbit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  OrbitRoute: typeof OrbitRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ReelsRoute: typeof ReelsRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orbit': {
      id: '/orbit'
      path: '/orbit'
      fullPath: '/orbit'
      preLoaderRoute: typeof OrbitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orbit/': {
      id: '/orbit/'
      path: '/'
      fullPath: '/orbit/'
      preLoaderRoute: typeof OrbitIndexRouteImport
      parentRoute: typeof OrbitRoute
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orbit/privacy': {
      id: '/orbit/privacy'
      path: '/privacy'
      fullPath: '/orbit/privacy'
      preLoaderRoute: typeof OrbitPrivacyRouteImport
      parentRoute: typeof OrbitRoute
    }
    '/orbit/create': {
      id: '/orbit/create'
      path: '/create'
      fullPath: '/orbit/create'
      preLoaderRoute: typeof OrbitCreateRouteImport
      parentRoute: typeof OrbitRoute
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrbitRouteChildren {
  OrbitCreateRoute: typeof OrbitCreateRoute
  OrbitPrivacyRoute: typeof OrbitPrivacyRoute
  OrbitIndexRoute: typeof OrbitIndexRoute
}

const OrbitRouteChildren: OrbitRouteChildren = {
  OrbitCreateRoute: OrbitCreateRoute,
  OrbitPrivacyRoute: OrbitPrivacyRoute,
  OrbitIndexRoute: OrbitIndexRoute,
}

const OrbitRouteWithChildren = OrbitRoute._addFileChildren(OrbitRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  OrbitRoute: OrbitRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ReelsRoute: ReelsRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
