// This file is automatically generated.
// Safe Supabase client configuration for browser and SSR environments.

import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  (typeof process !== "undefined"
    ? process.env?.VITE_SUPABASE_URL || process.env?.SUPABASE_URL
    : undefined);

const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  (typeof process !== "undefined"
    ? process.env?.VITE_SUPABASE_PUBLISHABLE_KEY ||
      process.env?.VITE_SUPABASE_ANON_KEY ||
      process.env?.SUPABASE_PUBLISHABLE_KEY ||
      process.env?.SUPABASE_ANON_KEY
    : undefined);

const isBrowser =
  typeof window !== "undefined" &&
  typeof window.localStorage !== "undefined";

function getStorage() {
  if (!isBrowser) return undefined;

  return window.localStorage;
}

let supabaseClient: SupabaseClient<Database> | undefined;

function createSupabaseClient(): SupabaseClient<Database> {
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.error(
      "Supabase environment variables are missing. Please configure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY."
    );

    return createClient<Database>(
      "https://placeholder.supabase.co",
      "placeholder-key",
      {
        auth: {
          persistSession: false,
          autoRefreshToken: false,
          detectSessionInUrl: false,
        },
      }
    );
  }

  return createClient<Database>(
    SUPABASE_URL,
    SUPABASE_PUBLISHABLE_KEY,
    {
      auth: {
        storage: getStorage(),
        persistSession: isBrowser,
        autoRefreshToken: isBrowser,
        detectSessionInUrl: isBrowser,
      },
    }
  );
}

export const supabase = new Proxy({} as SupabaseClient<Database>, {
  get(_target, prop, receiver) {
    if (!supabaseClient) {
      supabaseClient = createSupabaseClient();
    }

    return Reflect.get(supabaseClient, prop, receiver);
  },
});
